#!/usr/bin/env bash

echo "# git-nuke" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/atom06/git-nuke.git
git push -u origin main